# Site settings
title: George Stathopoulos
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: George Stathopoulos
user_description: Data Scientist and Instructor with experience in using data to drive business decisions and teaching the next generation of data scientists. Skilled in machine learning, statistical modeling, and data visualization. Proven track record of using data to improve operational efficiency and drive revenue growth. Strong communication skills and ability to translate complex data findings into actionable insights for non-technical stakeholders. Experienced in Python, R, SQL, and Tableau. Proven experience in teaching and mentoring students, both in-person and online, to become proficient data scientists.
user_title: Data Scientist & Instructor
email: geostatho@gmail.com
# twitter_username: lorem_ipsum
instagram_username: geo_statho
facebook_username: geo_statho
linkedin_username: -george-stathopoulos
github_username:  GeorgeStathopoulos
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

